Algoritmo "Concatenacao"


// Professor   : Cleison Ferreira
// Descrição   : Aprendendo Sobre estrutura de controle
// Autor(a)    : Wendell Gomes
// Data atual  : 10/09/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome:")
   leia(nome)
   escreval("Digite o numero:")
   leia(numero)
   
   escreval(nome, " : ", numero)

Fimalgoritmo