Algoritmo "Operadores Relacionais"


// Professor   : Cleison Ferreira
// Descrição   : Aprendendo Sobre estrutura de controle
// Autor(a)    : Wendell Gomes
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis 
   nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01 := 10
   nota02 := 15
   
   se (nota01 <> nota02) entao
      escreval("Nota 01 diferente")
   senao
      escreval("Nota 01 igual")
   fimse

Fimalgoritmo