Algoritmo "Meu Primeiro Algoritimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Wendell Neri Gomes Pedra
// Data atual  : 07/09/2021
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("Resultado", nota)

Fimalgoritmo