Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Ferreira de Melo
// Descrição   : Aprendendo sobre Variaveis
// Autor(a)    : Wendell Neri
// Data atual  : 07/09/2021
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



Fimalgoritmo